PROG = 7zG
IS_NOT_STANDALONE = 1

# Interface graphique : sous-systeme Windows (point d'entree WinMain)
LDFLAGS_STATIC_3 = -mwindows
MY_LIBS = -lhtmlhelp

LOCAL_FLAGS = \
  -DZ7_LANG \
  -DZ7_EXTERNAL_CODECS \
  -DZ7_DEVICE_FILE \

GUI_OBJS = \
  $O/BenchmarkDialog.o \
  $O/CompressDialog.o \
  $O/ExtractDialog.o \
  $O/ExtractGUI.o \
  $O/GUI.o \
  $O/HashGUI.o \
  $O/UpdateCallbackGUI.o \
  $O/UpdateCallbackGUI2.o \
  $O/UpdateGUI.o \

COMMON_OBJS = \
  $O/CommandLineParser.o \
  $O/CRC.o \
  $O/DynLimBuf.o \
  $O/IntToString.o \
  $O/Lang.o \
  $O/ListFileUtils.o \
  $O/MyString.o \
  $O/MyVector.o \
  $O/NewHandler.o \
  $O/StringConvert.o \
  $O/StringToInt.o \
  $O/UTFConvert.o \
  $O/Wildcard.o \

WIN_OBJS = \
  $O/Clipboard.o \
  $O/CommonDialog.o \
  $O/DLL.o \
  $O/ErrorMsg.o \
  $O/FileDir.o \
  $O/FileFind.o \
  $O/FileIO.o \
  $O/FileLink.o \
  $O/FileName.o \
  $O/FileSystem.o \
  $O/MemoryGlobal.o \
  $O/MemoryLock.o \
  $O/PropVariant.o \
  $O/PropVariantConv.o \
  $O/Registry.o \
  $O/ResourceString.o \
  $O/Shell.o \
  $O/Synchronization.o \
  $O/System.o \
  $O/SystemInfo.o \
  $O/TimeUtils.o \
  $O/Window.o \

WIN_CTRL_OBJS = \
  $O/ComboBox.o \
  $O/Dialog.o \
  $O/ListView.o \

7ZIP_COMMON_OBJS = \
  $O/CreateCoder.o \
  $O/FilePathAutoRename.o \
  $O/FileStreams.o \
  $O/FilterCoder.o \
  $O/LimitedStreams.o \
  $O/MethodProps.o \
  $O/MultiOutStream.o \
  $O/ProgressUtils.o \
  $O/PropId.o \
  $O/StreamObjects.o \
  $O/StreamUtils.o \
  $O/UniqBlocks.o \

UI_COMMON_OBJS = \
  $O/ArchiveCommandLine.o \
  $O/ArchiveExtractCallback.o \
  $O/ArchiveOpenCallback.o \
  $O/Bench.o \
  $O/DefaultName.o \
  $O/EnumDirItems.o \
  $O/Extract.o \
  $O/ExtractingFilePath.o \
  $O/HashCalc.o \
  $O/LoadCodecs.o \
  $O/OpenArchive.o \
  $O/PropIDUtils.o \
  $O/SetProperties.o \
  $O/SortUtils.o \
  $O/TempFiles.o \
  $O/Update.o \
  $O/UpdateAction.o \
  $O/UpdateCallback.o \
  $O/UpdatePair.o \
  $O/UpdateProduce.o \
  $O/WorkDir.o \
  $O/ZipRegistry.o \

AR_COMMON_OBJS = \
  $O/ItemNameUtils.o \
  $O/OutStreamWithCRC.o \

FM_OBJS = \
  $O/BrowseDialog.o \
  $O/ComboDialog.o \
  $O/EditDialog.o \
  $O/ExtractCallback.o \
  $O/FormatUtils.o \
  $O/HelpUtils.o \
  $O/LangUtils.o \
  $O/ListViewDialog.o \
  $O/MemDialog.o \
  $O/OpenCallback.o \
  $O/OverwriteDialog.o \
  $O/PasswordDialog.o \
  $O/ProgramLocation.o \
  $O/ProgressDialog2.o \
  $O/PropertyName.o \
  $O/RegistryUtils.o \
  $O/SplitUtils.o \
  $O/StringUtils.o \
  $O/SysIconUtils.o \

EXPLORER_OBJS = \
  $O/MyMessages.o \

COMPRESS_OBJS = \
  $O/CopyCoder.o \

C_OBJS = \
  $O/Alloc.o \
  $O/CpuArch.o \
  $O/DllSecur.o \
  $O/Sort.o \
  $O/Threads.o \
  $O/7zCrc.o \
  $O/7zCrcOpt.o \
  $O/Transpose.o \
  $O/LzmaEnc.o \
  $O/LzFind.o \
  $O/LzFindMt.o \
  $O/LzFindOpt.o \
  $O/Ppmd7.o \
  $O/Ppmd7Enc.o \

OBJS = \
  $(C_OBJS) \
  $(COMMON_OBJS) \
  $(WIN_OBJS) \
  $(WIN_CTRL_OBJS) \
  $(COMPRESS_OBJS) \
  $(AR_COMMON_OBJS) \
  $(7ZIP_COMMON_OBJS) \
  $(UI_COMMON_OBJS) \
  $(FM_OBJS) \
  $(EXPLORER_OBJS) \
  $(GUI_OBJS) \
  $O/resource.o \

include ../../7zip_gcc.mak
